version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: shopx_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: shopxdb
    ports:
      - "5433:5433"
    volumes:
      - shopx_pgdata:/var/lib/postgresql/data

  seq:
    image: datalust/seq:2024
    container_name: shopx_seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"

volumes:
  shopx_pgdata:
