version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: shopx
      POSTGRES_PASSWORD: shopx
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  seq:
    image: datalust/seq:2024
    environment:
      - ACCEPT_EULA=Y
    ports: ["5341:80"]
volumes:
  pgdata:
